### ISSUE TITLE
maybe compatibility issue?

### ISSUE THREAD

**Issue by FudgeDumbo** [nakanotti/CocoaInput#2]
so with.. sign edit mod with clicks
with sign edit mod, right click on the sign crashes the game

I know you are not the main coder xD but since you are the guy knows the modding to update
thought maybe give a try to give you errors that I am getting :)

Thank you and great work!

**Comment by FudgeDumbo** [comment]
here is the error msg

The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Cannot invoke "jp.axer.cocoainput.wrapper.SignEditScreenWrapper.renewCursorCounter()" because "this.wrapper" is null
Exit Code: -1

**Comment by nakanotti** [comment]
Please, check following plugins.
[CocoaInput-1.19-4.0.5-PREVIEW2.zip](https://github.com/nakanotti/CocoaInput/files/8997573/CocoaInput-1.19-4.0.5-PREVIEW2.zip)

**Comment by FudgeDumbo** [comment]
still crashing here is the more detail crash report

Time: 22. 6. 27. 오후 11:13
Description: Ticking screen

java.lang.NullPointerException: Cannot invoke "jp.axer.cocoainput.wrapper.SignEditScreenWrapper.renewCursorCounter()" because "this.wrapper" is null
	at net.minecraft.class_498.redirect$zzf000$injectCurosr(class_498.java:524)
	at net.minecraft.class_498.method_25393(class_498.java:88)
	at net.minecraft.class_310.method_1572(class_310.java:1783)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_310.method_1574(class_310.java:1783)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_498.redirect$zzf000$injectCurosr(class_498.java:524)
	at net.minecraft.class_498.method_25393(class_498.java:88)
	at net.minecraft.class_310.method_1572(class_310.java:1783)
	at net.minecraft.class_437.method_25412(class_437.java:491)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_498
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_310.method_1574(class_310.java:1783)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by nakanotti** [comment]
Thank you for details.

> with sign edit mod, right click on the sign crashes the game

This mod?
https://www.curseforge.com/minecraft/mc-mods/edit-sign

**Comment by FudgeDumbo** [comment]
yes~

**Comment by nakanotti** [comment]
Can you tell me the version information of the mod in use that can confirm the reproduction of the crash?

**Comment by FudgeDumbo** [comment]
so far 0.14.8
fabric loader
fabric api 0.56.3+1.19
cloth-config-7.0.72-fabric
editsign-1.19-2.4.1
lithium 0.8.0

**Comment by nakanotti** [comment]
Unfortunately I couldn't reproduce it.
Would you like to reproduce it in a new world?

**Comment by nakanotti** [comment]
Retry it.
[CocoaInput-1.19-4.0.5-PREVIEW2.zip](https://github.com/nakanotti/CocoaInput/files/9000655/CocoaInput-1.19-4.0.5-PREVIEW2.zip)
But the result may not change...

**Comment by FudgeDumbo** [comment]
sorry found the issue. it is not compatible with stendhal mod.
without stendhal mod it works fine.
I rather take out the stendhal and keep your mod xD
https://www.curseforge.com/minecraft/mc-mods/stendhal/files

thank you!
you are awesome~

**Comment by nakanotti** [comment]
It was good to find it.
I will investigate it as a compatibility issue.

**Comment by nakanotti** [comment]
```
[14:35:25] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at net.minecraft.class_437.method_25412(class_437.java:496) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1783) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "jp.axer.cocoainput.wrapper.SignEditScreenWrapper.renewCursorCounter()" because "this.wrapper" is null
	at net.minecraft.class_498.redirect$zzf000$injectCurosr(class_498.java:524) ~[client-intermediary.jar:?]
	at net.minecraft.class_498.method_25393(class_498.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1572(class_310.java:1783) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
	... 7 more
```
ん？init()すっ飛ばして来てる？

**Comment by nakanotti** [comment]
Please, Check it. > @FudgeDumbo 
https://github.com/nakanotti/CocoaInput/pull/6

**Comment by nakanotti** [comment]
2週間以上、ほぼ毎日使っていましたが特に問題が無いため解決済みとします。
masterにマージされました。＞ 505e8fba7aaacfc493c4ea4e174f5cee8592f520
