### ISSUE TITLE
1.20.2 is supported now.

### ISSUE THREAD

**Issue by nakanotti** [nakanotti/CocoaInput#32]
** Describe the bug **
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_342.method_1883(int)'
	at jp.axer.cocoainput.wrapper.EditBoxWrapper.setCursorPos(EditBoxWrapper.java:53)
	at jp.axer.cocoainput.plugin.IMEReceiver.insertText(IMEReceiver.java:40)
	at jp.axer.cocoainput.arch.win.WinIMEOperator.setFocused(WinIMEOperator.java:36)
	at jp.axer.cocoainput.arch.win.WinController.screenOpenNotify(WinController.java:96)
	at jp.axer.cocoainput.CocoaInput.distributeScreen(CocoaInput.java:65)
	at jp.axer.cocoainput.loader.FabricLoader.onChangeScreen(FabricLoader.java:30)
	at net.minecraft.class_310.handler$zze000$cocoainput$setScreen(class_310.java:3084)
	at net.minecraft.class_310.method_1507(class_310.java)
	at net.minecraft.class_423.method_38530(class_423.java:86)
	at net.minecraft.class_310.method_1574(class_310.java:1917)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

** Describe the environment ** 
 - OS: Windows 11 (amd64) version 10.0
 - Arch: x86_64
 - IME: Microsoft IME
 - Minecraft 1.20.2
 - ModVersion CocoaInput-1.20-fabric-4.0.9-PREVIEW2.jar
 - ModSetting fabric-loader-0.14.22-1.20.2

**To Reproduce**
1. Go to 'シングルプレイ...'
2. Click on EditBox
3. Error occured

**Logs(URL)**
 No logs no solutions

**Additional context**

**Comment by nakanotti** [comment]
EditBox 周りが変わっているせいっぽい。
```
E:\P\private\CocoaInput\src\main\java\jp\axer\cocoainput\mixin\EditBoxMixin.java:28: 警告:Unable to determine descriptor for @Inject target method
         @Inject(method="tick",at=@At("HEAD"),cancellable=true)
         ^
E:\P\private\CocoaInput\src\main\java\jp\axer\cocoainput\wrapper\EditBoxWrapper.java:33: エラー: シンボルを見つけられません
        if (cursorVisible) owner.frame++;
                                ^
  シンボル:   変数 frame
  場所: タイプEditBoxの変数 owner
E:\P\private\CocoaInput\src\main\java\jp\axer\cocoainput\wrapper\EditBoxWrapper.java:45: エラー: シンボルを見つけられません
                owner.frame=6;
                     ^
  シンボル:   変数 frame
  場所: タイプEditBoxの変数 owner
E:\P\private\CocoaInput\src\main\java\jp\axer\cocoainput\wrapper\EditBoxWrapper.java:53: エラー: クラス EditBoxのメソッド moveCursorToは指定された型に適用できません。
                owner.moveCursorTo(p);
                     ^
  期待値: int,boolean
  検出値:    int
  理由: 実引数リストと仮引数リストの長さが異なります
E:\P\private\CocoaInput\src\main\java\jp\axer\cocoainput\util\TinyConfig.java:212: エラー: クラス Screenのメソッド renderBackgroundは指定された型に適用できません。
            this.renderBackground(guiGraphics);
                ^
  期待値: GuiGraphics,int,int,float
  検出値:    GuiGraphics
  理由: 実引数リストと仮引数リストの長さが異なります
エラー4個
警告1個
```

**Comment by nakanotti** [comment]
[Released](https://github.com/nakanotti/CocoaInput/releases/tag/1.20.2-PREVIEW2)
